name: Create Release with Latest URL

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release URL
        id: get_url
        run: |
          REPO="ungoogled-software/ungoogled-chromium-windows"
          FILE_NAME="ungoogled-chromium_*.zip"

          # Fetch the latest release information
          LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$REPO/releases/latest")

          # Extract the download URL for the ZIP file
          ZIP_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | test("ungoogled-chromium_.*_windows_x64.zip")) | .browser_download_url')
          echo "Latest ZIP URL: $ZIP_URL"

          VERSION=$(echo "$LATEST_RELEASE" | jq -r ".tag_name")

          # Output the URL
          echo "Latest ZIP URL: $ZIP_URL"

          # Set outputs for later steps
          echo "::set-output name=zip_url::$ZIP_URL"
          echo "::set-output name=version::$VERSION"

      - name: Create Release
        run: |
          gh release create "${{ steps.get_url.outputs.version }}" updateurl.txt --title "Release ${{ steps.get_url.outputs.version }}" --notes "Latest release URL: ${{ steps.get_url.outputs.zip_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
